---
# tasks file for ansible-role-deluge-daemon

- name: install deluge packages
  package:
    name:
      - deluged
      - deluge-web
      - deluge-console
    state: present

- name: Add the deluge user
  user:
    name: "{{ deluge_user }}"
    home: "{{ deluge_user_home | default(omit) }}"
    comment: Deluge Service

- name: Add system deluged.service
  template:
    src: deluged.service.j2
    dest: /etc/systemd/system/deluged.service

- name: Enable deluged.service
  systemd:
    name: deluged.service
    enabled: yes
    state: started

- name: Add system deluge-web.service
  template:
    src: deluge-web.service.j2
    dest: /etc/systemd/system/deluge-web.service

- name: enable deluge-web.service
  systemd:
    name: deluge-web.service
    enabled: yes
    state: started

- name: sleep for 2 seconds and continue with play
  wait_for:
    timeout: 2
  delegate_to: localhost
  become: no

- name: Configure deluge (stop deluge if config change is required)
  template:
    src: core.conf.j2
    dest: "{{ deluge_user_home }}/.config/deluge/core.conf"
    owner: "{{ deluge_user }}"
    group: "{{ deluge_group }}"
  notify: stop deluged

- name: flush handlers because deluge needs to be stopped for config changes
  meta: flush_handlers

- name: Configure deluge
  template:
    src: core.conf.j2
    dest: "{{ deluge_user_home }}/.config/deluge/core.conf"
    owner: "{{ deluge_user }}"
    group: "{{ deluge_group }}"
  notify: restart deluged
